development:
  adapter: postgresql
  encoding: unicode
  database: sigridberkebile-stoiser
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sigridberkebile-stoiser
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sigridberkebile-stoiser
  pool: 5
  username:
  password:
